name: noct_cinedex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  mocktail: ^1.0.4
  go_router: ^15.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/.env